export const DEPARTMENTS = [
    "ACCOUNTING",
    "AGRICULTURE",
    "ARCHITECTURE",
    "BANKING_AND_FINANCE",
    "BIOCHEMISTRY",
    "BUSINESS_ADMINISTRATION",
    "CHEMICAL_ENGINEERING",
    "CIVIL_ENGINEERING",
    "COMPUTER_ENGINEERING",
    "COMPUTER_SCIENCE",
    "ELECTRICAL_ENGINEERING",
    "MASS_COMMUNICATION",
    "MECHANICAL_ENGINEERING",
    "MEDICINE",
    "MICROBIOLOGY",
    "NURSING",
    "PHARMACY",
    "PHYSICS",
    "POLITICAL_SCIENCE",
    "PSYCHOLOGY",
    "PUBLIC_ADMINISTRATION",
    "SOCIOLOGY",
    "STATISTICS",
    "LAW",
    "ECONOMICS",
    "BUILDING",
    "ESTATE_MANAGEMENT",
    "SURVEYING",
    "URBAN_AND_REGIONAL_PLANNING",
    "FOOD_TECHNOLOGY",
    "SCIENCE_LAB_TECHNOLOGY",
    "HOSPITALITY_MANAGEMENT",
    "MARINE_ENGINEERING",
    "PRINTING_TECHNOLOGY",
] as const;

export const LEVELS = [
    "ND1",
    "ND2",
    "HND1",
    "HND2",
    "100",
    "200",
    "300",
    "400",
    "500",
    "PGD",
    "MASTERS",
    "PHD",
] as const;

export type Department = (typeof DEPARTMENTS)[number];
export type Level = (typeof LEVELS)[number];

export const DEPARTMENT_LABELS: Record<Department, string> = {
    ACCOUNTING: "Accounting",
    AGRICULTURE: "Agriculture",
    ARCHITECTURE: "Architecture",
    BANKING_AND_FINANCE: "Banking & Finance",
    BIOCHEMISTRY: "Biochemistry",
    BUSINESS_ADMINISTRATION: "Business Administration",
    CHEMICAL_ENGINEERING: "Chemical Engineering",
    CIVIL_ENGINEERING: "Civil Engineering",
    COMPUTER_ENGINEERING: "Computer Engineering",
    COMPUTER_SCIENCE: "Computer Science",
    ELECTRICAL_ENGINEERING: "Electrical Engineering",
    MASS_COMMUNICATION: "Mass Communication",
    MECHANICAL_ENGINEERING: "Mechanical Engineering",
    MEDICINE: "Medicine",
    MICROBIOLOGY: "Microbiology",
    NURSING: "Nursing",
    PHARMACY: "Pharmacy",
    PHYSICS: "Physics",
    POLITICAL_SCIENCE: "Political Science",
    PSYCHOLOGY: "Psychology",
    PUBLIC_ADMINISTRATION: "Public Administration",
    SOCIOLOGY: "Sociology",
    STATISTICS: "Statistics",
    LAW: "Law",
    ECONOMICS: "Economics",
    BUILDING: "Building",
    ESTATE_MANAGEMENT: "Estate Management",
    SURVEYING: "Surveying",
    URBAN_AND_REGIONAL_PLANNING: "Urban & Regional Planning",
    FOOD_TECHNOLOGY: "Food Technology",
    SCIENCE_LAB_TECHNOLOGY: "Science Lab Technology",
    HOSPITALITY_MANAGEMENT: "Hospitality Management",
    MARINE_ENGINEERING: "Marine Engineering",
    PRINTING_TECHNOLOGY: "Printing Technology",
};

export const LEVEL_LABELS: Record<Level, string> = {
    ND1: "ND 1",
    ND2: "ND 2",
    HND1: "HND 1",
    HND2: "HND 2",
    "100": "100 Level",
    "200": "200 Level",
    "300": "300 Level",
    "400": "400 Level",
    "500": "500 Level",
    PGD: "Post Graduate Diploma",
    MASTERS: "Masters",
    PHD: "PhD",
};

export const ORDER_STATUS = {
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED",
} as const;

export const WITHDRAWAL_STATUS = {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    PAID: "PAID",
} as const;
